/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Calender: typeof import('./src/components/calender.vue')['default']
    CustomSelect: typeof import('./src/components/customSelect.vue')['default']
    DetailSelector: typeof import('./src/components/detailSelector/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Selector: typeof import('./src/components/selector.vue')['default']
    Subnav: typeof import('./src/components/subnav.vue')['default']
    Subtask: typeof import('./src/components/subtask.vue')['default']
    Task: typeof import('./src/components/task.vue')['default']
    Test: typeof import('./src/components/test.vue')['default']
    Textarea: typeof import('./src/components/textarea.vue')['default']
    Time: typeof import('./src/components/time.vue')['default']
  }
}
